package main

// Generates data/world.d.lua, a Lua language server definition file for the world table that the
// backend exposes to scripts. Constants come from world.ScriptConstantTables() and function stubs
// come from the SCRIPT_LIBRARY entries in world/script_library.go, documented with the comment
// above each entry.

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"mud/world"
	"os"
	"sort"
	"strconv"
	"strings"
)

const LUA_DEFS_SCRIPT_LIBRARY_PATH = "world/script_library.go"
const LUA_DEFS_SCRIPT_LIBRARY_NAME = "SCRIPT_LIBRARY"

type luaDefsFunction struct {
	name string
	commentLines []string
}

func generateLuaDefs(path string) error {
	functions, err := luaDefsParseScriptLibrary(LUA_DEFS_SCRIPT_LIBRARY_PATH)
	if err != nil {
		return err
	}

	var output bytes.Buffer
	output.WriteString("---@meta\n")
	output.WriteString("-- Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("---@class world\n")
	output.WriteString("world = {}\n")

	for _, constantTable := range world.ScriptConstantTables() {
		output.WriteString("\n")
		output.WriteString(fmt.Sprintf("---@enum %s\n", constantTable.Name))
		output.WriteString(fmt.Sprintf("world.%s = {\n", constantTable.Name))
		for _, constant := range constantTable.Constants {
			output.WriteString(fmt.Sprintf("\t%s = %s,\n", constant.Name, strconv.Quote(constant.Value)))
		}
		output.WriteString("}\n")
	}

	for _, function := range functions {
		output.WriteString("\n")
		paramNames := []string{}
		for _, line := range function.commentLines {
			if strings.HasPrefix(line, "@") {
				output.WriteString(fmt.Sprintf("---%s\n", line))
			} else if line == "" {
				output.WriteString("---\n")
			} else {
				output.WriteString(fmt.Sprintf("--- %s\n", line))
			}

			if strings.HasPrefix(line, "@param ") {
				fields := strings.Fields(line)
				if len(fields) < 2 {
					return fmt.Errorf("function '%s' has a @param with no name", function.name)
				}
				paramNames = append(paramNames, strings.TrimSuffix(fields[1], "?"))
			}
		}
		output.WriteString(fmt.Sprintf("function world.%s(%s) end\n", function.name, strings.Join(paramNames, ", ")))
	}

	return os.WriteFile(path, output.Bytes(), 0644)
}

// Returns each entry of the script library along with its doc comment, sorted by name
func luaDefsParseScriptLibrary(path string) ([]luaDefsFunction, error) {
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	libraryLiteral := luaDefsFindScriptLibrary(file)
	if libraryLiteral == nil {
		return nil, fmt.Errorf("could not find %s in %s", LUA_DEFS_SCRIPT_LIBRARY_NAME, path)
	}

	// Comments inside a composite literal aren't attached to any node, so map each comment
	// group by the line it ends on and look up the group directly above each entry
	commentGroupsByEndLine := make(map[int]*ast.CommentGroup)
	for _, commentGroup := range file.Comments {
		commentGroupsByEndLine[fileSet.Position(commentGroup.End()).Line] = commentGroup
	}

	functions := []luaDefsFunction{}
	for _, element := range libraryLiteral.Elts {
		keyValue, ok := element.(*ast.KeyValueExpr)
		if !ok {
			return nil, fmt.Errorf("%s: unexpected element in %s", fileSet.Position(element.Pos()), LUA_DEFS_SCRIPT_LIBRARY_NAME)
		}
		keyLiteral, ok := keyValue.Key.(*ast.BasicLit)
		if !ok || keyLiteral.Kind != token.STRING {
			return nil, fmt.Errorf("%s: %s keys must be string literals", fileSet.Position(keyValue.Pos()), LUA_DEFS_SCRIPT_LIBRARY_NAME)
		}
		name, err := strconv.Unquote(keyLiteral.Value)
		if err != nil {
			return nil, err
		}

		commentGroup := commentGroupsByEndLine[fileSet.Position(keyValue.Pos()).Line - 1]
		if commentGroup == nil {
			return nil, fmt.Errorf("%s: script library function '%s' has no doc comment", fileSet.Position(keyValue.Pos()), name)
		}

		function := luaDefsFunction {
			name: name,
			commentLines: make([]string, 0, len(commentGroup.List)),
		}
		for _, comment := range commentGroup.List {
			if !strings.HasPrefix(comment.Text, "//") {
				return nil, fmt.Errorf("%s: doc comment for '%s' must use // comments", fileSet.Position(comment.Pos()), name)
			}
			line := strings.TrimPrefix(comment.Text, "//")
			line = strings.TrimPrefix(line, " ")
			function.commentLines = append(function.commentLines, strings.TrimRight(line, " \t"))
		}

		functions = append(functions, function)
	}

	if len(functions) == 0 {
		return nil, errors.New(LUA_DEFS_SCRIPT_LIBRARY_NAME + " has no entries")
	}

	sort.Slice(functions, func(i, j int) bool {
		return functions[i].name < functions[j].name
	})

	return functions, nil
}

func luaDefsFindScriptLibrary(file *ast.File) *ast.CompositeLit {
	for _, declaration := range file.Decls {
		genDecl, ok := declaration.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			continue
		}
		for _, spec := range genDecl.Specs {
			valueSpec := spec.(*ast.ValueSpec)
			for index, name := range valueSpec.Names {
				if name.Name != LUA_DEFS_SCRIPT_LIBRARY_NAME || index >= len(valueSpec.Values) {
					continue
				}
				literal, ok := valueSpec.Values[index].(*ast.CompositeLit)
				if ok {
					return literal
				}
			}
		}
	}

	return nil
}
