// Code generated by tygo. DO NOT EDIT.
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-interface, @typescript-eslint/no-empty-object-type */

//////////
// source: a_constants.go

export const WORLD_SECONDS_PER_UPDATE = 3;
export const WORLD_MAX_ROOMS: number /* int */ = 1024;

//////////
// source: character.go

export const CHARACTER_ROOMS_DISCOVERED_BYTE_SIZE: number /* int */ = WORLD_MAX_ROOMS / 8;
export interface CharacterSheet {
  Name: string;
  Race: RaceId;
  Class: ClassId;
  Job: JobId;
}
export interface CharacterEquippedSpell {
  EquipCount: number /* int32 */;
  Casts: number /* int32 */;
  IsKnown: boolean;
}
export interface Character {
  PlayerId: number /* int */;
  Race: RaceId;
  Class: ClassId;
  Job: JobId;
  SpellsEquipped: { [key: Spell]: CharacterEquippedSpell | undefined};
  SpellsKnown: Spell[];
  RecipesKnown: Recipe[];
  RoomsDiscovered: string /* []byte */;
  Data: MobData;
}

//////////
// source: character_class.go

export type ClassId = number /* int */;
export const CLASS_WARRIOR = 0;
export const CLASS_THIEF = 1;
export const CLASS_WIZARD = 2;
export const CLASS_PRIEST = 3;
export interface ClassData {
  Name: string;
  Stats: StatBlock;
  Scaling: StatBlock;
}

//////////
// source: character_job.go

export type JobId = number /* int */;
export const JOB_ALCHEMIST = 0;
export const JOB_BLACKSMITH = 1;
export const JOB_ENCHANTER = 2;
export interface JobData {
  Name: string;
  Stats: StatBlock;
  Scaling: StatBlock;
}

//////////
// source: character_name.go

export const CHARACTER_NAME_MAX: number /* int */ = 32;
export const CHARACTER_NAME_MIN_LETTERS: number /* int */ = 2;

//////////
// source: character_race.go

export type RaceId = number /* int */;
export const RACE_HUMAN = 0;
export const RACE_ELF = 1;
export const RACE_DWARF = 2;
export const RACE_HOBBIT = 3;
export const RACE_ORC = 4;
export const RACE_GREMLIN = 5;
export interface RaceData {
  Name: string;
  Stats: StatBlock;
}

//////////
// source: direction.go

export type Direction = number /* int */;
export const DIRECTION_NORTH = 0;
export const DIRECTION_EAST = 1;
export const DIRECTION_SOUTH = 2;
export const DIRECTION_WEST = 3;
export const DIRECTION_COUNT = 4;

//////////
// source: drop_table.go

export interface DropTableEntry {
  ItemId: ItemId;
  AmountRange: Int32Range;
  Durability: number /* float32 */;
  DropChance: number /* float32 */;
}
export interface DropTable {
  Entries: DropTableEntry[];
}

//////////
// source: equipment.go

export type EquipmentSlot = number /* int */;
export const EQUIPMENT_SLOT_MAIN_HAND = 0;
export const EQUIPMENT_SLOT_OFF_HAND = 1;
export const EQUIPMENT_SLOT_OUTFIT = 2;
export const EQUIPMENT_SLOT_ACCESSORY = 3;
export const EQUIPMENT_SLOT_COUNT = 4;
export interface Equipment {
  IsSlotInUse: boolean[];
  SlotItem: Item[];
  /**
   * This field is private it will not be saved in world json
   * Instead, stat bonuses are recalculated when a character logins
   * This way if an item gets a balance patch, players will get the patch applied
   * to them when they login
   */
  StatBonuses: StatBlock;
}

//////////
// source: event.go

export type EventType = number /* int */;
export const EVENT_TYPE_MESSAGE = 0;
export const EVENT_TYPE_MOB_MOVE = 1;
export const EVENT_TYPE_MOB_DEATH = 2;
export const EVENT_TYPE_MOB_SET_TARGET = 3;
export const EVENT_TYPE_COUNT = 4;
export interface Event {
  EventType: EventType;
  Data: any;
}
export interface EventMessage {
  ToPlayers: number /* int */[];
  Message: string;
}
export interface EventMobMove {
  MobHandle: MobHandle;
  FromRoom: number /* int */;
  ToRoom: number /* int */;
}
export interface EventMobDeath {
  PlayerId: number /* int */;
  MobHandle: MobHandle;
}
export interface EventMobSetTarget {
  Attacker: MobHandle;
  Defender: MobHandle;
}
export interface MessageRoomOptions {
}

//////////
// source: inventory.go

export interface Inventory {
  Items: Item[];
}

//////////
// source: item.go

export type ItemId = number /* int32 */;
export const ITEM_GOLD = 0;
export const ITEM_DUMMY_MATERIAL = 1;
export const ITEM_SWORD = 2;
export const ITEM_AXE = 3;
export const ITEM_SPELLBOOK_FIREBOLT = 4;
export const ITEM_SPELLBOOK_CURE = 5;
export const ITEM_POTION_HEALTH = 6;
export const ITEM_POTION_MANA = 7;
export const ITEM_RECIPE_HEALTH_POT = 8;
export const ITEM_RECIPE_MANA_POT = 9;
export const ITEM_RECIPE_SWORD = 10;
export const ITEM_RECIPE_AXE = 11;
export interface Item {
  Id: ItemId;
  Amount: number /* int32 */;
  Durability: number /* int32 */;
}
export type ItemType = number /* int */;
export const ITEM_TYPE_CONSUMABLE = 0;
export const ITEM_TYPE_EQUIPMENT_ONE_HANDED = 1;
export const ITEM_TYPE_EQUIPMENT_TWO_HANDED = 2;
export const ITEM_TYPE_EQUIPMENT_OUTFIT = 3;
export const ITEM_TYPE_EQUIPMENT_ACCESSORY = 4;
export const ITEM_TYPE_EQUIPMENT_SPELLBOOK = 5;
export const ITEM_TYPE_SPELL_SCROLL = 6;
export const ITEM_TYPE_RECIPE = 7;
export const ITEM_TYPE_MISC = 8; // Indicates an item which has no special properties, like gold or a material
export interface ItemDataConsumable {
}
export interface ItemDataSpellScroll {
  Spell: Spell;
}
export interface ItemDataWeapon {
  Damage: number /* int32 */;
  MaxDurability: number /* int32 */;
  StatBonuses: StatBlock;
  StatRequirements: StatBlock;
}
export interface ItemDataOutfit {
  Armor: number /* int32 */;
  MaxDurability: number /* int32 */;
  StatBonuses: StatBlock;
  StatRequirements: StatBlock;
}
export interface ItemDataAccessory {
  StatBonuses: StatBlock;
  StatRequirements: StatBlock;
}
export interface ItemDataSpellbook {
  Spell: Spell;
  StatRequirements: StatBlock;
}
export interface ItemDataRecipe {
  Recipe: Recipe;
}
export interface ItemData {
  Name: string;
  Description: string;
  ItemType: ItemType;
  Data: any;
}

//////////
// source: mob.go

export const MOB_PLAYER_NONE = -1;
/**
 * Making Evasion K higher makes evasion chance smaller
 * Making this smaller makes evasion chance greater
 * Evasion chance of target = T / (T + (A * K))
 * Where T is target AGI and A is attacker AGI
 */
export const MOB_EVASION_K: number /* float32 */ = 6.0;
/**
 * Making Crit K higher increases the likelihood of crits
 * Crit chance =  (AGI / 50) * 0.33
 * 			   => AGI * (0.33 / 50)
 * A mob with a base AGI of 12 and high crit scaling will have 50 AGI at level 20,
 * so 50 is roughly the "max agility" a mob can have
 */
export const MOB_CRIT_K: number /* float32 */ = 0.33 / 50.0;
export const MOB_CRIT_DAMAGE_MULTIPLIER: number /* float32 */ = 1.5;
export type MobMode = number /* int32 */;
export const MOB_MODE_IDLE: MobMode = 0;
export const MOB_MODE_ATTACK: MobMode = 1;
export const MOB_MODE_CAST: MobMode = 2;
export const MOB_MODE_USE_ITEM: MobMode = 3;
export const MOB_MODE_CRAFT_ITEM: MobMode = 4;
export interface Mob {
  PlayerCharacter?: Character;
  Npc?: Npc;
  Handle: MobHandle;
  Data: MobData;
  Mode: MobMode;
  Target: MobHandle;
}

//////////
// source: mob_array.go

export interface MobHandle {
  Id: number /* uint32 */;
  Generation: number /* uint32 */;
}
export interface MobIndex {
}
export interface MobArray {
}

//////////
// source: mob_data.go

export const MOB_MAX_LEVEL: number /* int32 */ = 3;
export const MOB_EXP_PER_LEVEL: number /* int32 */ = 300;
/**
 * Making Cast K higher increases how effective intelligence is at reducing spell learn-time
 * Spell Casts to learn = Base + (1 - (INT / 50.0) * 0.75)
 * 					    => Base * (1 - INT * (0.75 / 50.0))
 * Where Base is the spell's base casts to learn
 * Higher intelligence therefore reduces the number of casts it takes to learn the spell
 */
export const MOB_CASTS_TO_LEARN_K: number /* float32 */ = 0.75 / 50.0;
export interface MobData {
  Name: string;
  Room: number /* int */;
  Level: number /* int32 */;
  Experience: number /* int32 */;
  ExperienceToNextLevel: number /* int32 */;
  Stats: StatBlock;
  Health: number /* int32 */;
  Mana: number /* int32 */;
  Spells: Spell[];
  Inventory: Inventory;
  Equipment: Equipment;
}

//////////
// source: npc.go

/**
 * Rather than reset the NPC's sleepy timer after combat,
 * we instead apply this adrenaline number to their sleepy timer,
 * so sleepy time is delayed but not completely reset
 */
export const NPC_SLEEPY_ADRENALINE_DURATION: number /* int32 */ = (5 * 60) / WORLD_SECONDS_PER_UPDATE;
export const NPC_SURPRISE_DURATION: number /* int32 */ = 1;
export type NpcMode = number /* int */;
export const NPC_MODE_DEAD = 0;
export const NPC_MODE_IDLE = 1;
export const NPC_MODE_SURPRISE = 2;
export const NPC_MODE_AGGRO = 3;
export const NPC_MODE_SLEEP = 4;
export type NpcMovementType = number /* int */;
export const NPC_MOVEMENT_TYPE_SENTINEL = 0;
export const NPC_MOVEMENT_TYPE_WANDER = 1;
/**
 * This could be replaced with a fine-grained number later
 */
export type NpcDisposition = number /* int */;
export const NPC_DISPOSITION_NEUTRAL = 0;
export const NPC_DISPOSITION_HOSTILE = 1;
export interface Npc {
  /**
   * NPC "config" variables - These are public and saved to world JSON
   */
  Type: NpcType;
  LevelRange: Int32Range;
  StartingDisposition: NpcDisposition;
  MovementType: NpcMovementType;
  Behavior: Behavior;
  SpawnRoom: number /* int */;
  RespawnDuration: number /* int32 */;
  SleepDuration: number /* int32 */;
  AwakeDuration: number /* int32 */;
  MovementStepDuration: number /* int32 */;
  DropTable: DropTable;
}

//////////
// source: npc_behavior.go

export type BehaviorEventType = number /* int */;
export const BEHAVIOR_EVENT_TYPE_ATTACKED = 0;
export const BEHAVIOR_EVENT_TYPE_PLAYER_ENTERED = 1;
export const BEHAVIOR_EVENT_TYPE_ITEM_GIVEN = 2;
export interface BehaviorEventAttacked {
  AttackerHandle: MobHandle;
}
export interface BehaviorEventPlayerEntered {
  PlayerHandle: MobHandle;
}
export interface BehaviorEventItemGiven {
  PlayerHandle: MobHandle;
  AddedToIndex: number /* int */;
  Amount: number /* int32 */;
}
export interface BehaviorEvent {
  Type: BehaviorEventType;
  Data: any;
}
export type BehaviorHooks = any;
export interface Behavior {
  Hooks: BehaviorHooks;
}
export interface BehaviorJson {
  Type: string;
  Data: BehaviorHooks;
}
export interface BehaviorJson {
  Type: string;
  Data: any /* json.RawMessage */;
}

//////////
// source: npc_behavior_troll.go

export const BEHAVIOR_TROLL_ANGRY_DURATION = (5 * 60) / WORLD_SECONDS_PER_UPDATE;
export const BEHAVIOR_TROLL_PEACE_DURATION = (5 * 60) / WORLD_SECONDS_PER_UPDATE;
export interface BehaviorTroll {
  ExitToBlock: Direction;
  Toll: Item;
}

//////////
// source: npc_data.go

export type NpcType = number /* int */;
export const NPC_TYPE_GOLBIN = 0;
export const NPC_TYPE_TROLL = 1;
export interface NpcData {
}

//////////
// source: range.go

export interface Int32Range {
  Min: number /* int32 */;
  Max: number /* int32 */;
}
export interface Float32Range {
  Min: number /* float32 */;
  Max: number /* float32 */;
}

//////////
// source: recipe.go

export const RECIPE_OUTPUT_MAX_DURABILITY = -1;
export type Recipe = number /* int */;
export const RECIPE_HEALTH_POTION = 0;
export const RECIPE_MANA_POTION = 1;
export const RECIPE_CURE_BOOK = 2;
export const RECIPE_FIREBOLT_BOOK = 3;
export const RECIPE_SWORD = 4;
export const RECIPE_AXE = 5;
export interface RecipeMaterial {
  Id: ItemId;
  Amount: number /* int32 */;
}
export interface RecipeData {
  Name: string;
  Job: JobId;
  Level: number /* int32 */;
  Materials: RecipeMaterial[];
  Output: Item;
}

//////////
// source: room.go

export const ROOM_NONE: number /* int */ = -1;
export const CHEST_CORPOSE_DECAY_DURATION = 30 / WORLD_SECONDS_PER_UPDATE;
export type ChestType = number /* int */;
export const CHEST_TYPE_CHEST = 0;
export const CHEST_TYPE_CORPSE = 1;
export interface Chest {
  Name: string;
  Type: ChestType;
  Timer: number /* int32 */;
  RespawnDuration: number /* int32 */;
  DropTable: DropTable;
  Inventory: Inventory;
}
export interface Room {
  Name: string;
  Description: string;
  Exits: number /* int */[];
  ExitIsLocked: boolean[];
  IsSafeZone: boolean;
  DropTable: DropTable;
  Inventory: Inventory;
  Chests: Chest[];
}

//////////
// source: spell.go

export type Spell = number /* int32 */;
export const SPELL_FIREBOLT = 0;
export const SPELL_CURE = 1;
export interface SpellData {
  Name: string;
  Description: string;
  CastsToLearn: number /* int32 */;
  ManaCost: number /* int32 */;
  CastTime: number /* int32 */;
  CanTargetPlayers: boolean;
}

//////////
// source: stat_block.go

export interface StatBlock {
  Vitality: number /* int32 */;
  Strength: number /* int32 */;
  Agility: number /* int32 */;
  Intelligence: number /* int32 */;
  Faith: number /* int32 */;
}

//////////
// source: world.go

export interface World {
  Rooms: Room[];
  Npcs: Npc[];
}

//////////
// source: world_save.go

export const WORLD_SAVES_FOLDER: string = "./saves";
export const WORLD_CHARACTER_SAVES_FOLDER: string = WORLD_SAVES_FOLDER + "/characters";
export const WORLD_SAVE_PATH: string = WORLD_SAVES_FOLDER + "/world.json";
export interface WorldSavePlayerData {
  Characters: string[];
}
