---@meta
-- Code generated by go generate; DO NOT EDIT.

---@class world
world = {}

---An opaque reference to a mob. Compare with ==. It may refer to a mob that no longer exists; check with world.mob_exists.
---@class MobHandle

---@type number
world.SPELL_CAST_TIME_INSTANT = 0

---@type boolean
world.NPC_EVENT_PREVENT_DEFAULT = true

---@enum ItemKind
world.ItemKind = {
	CONSUMABLE = "Consumable",
	EQUIPMENT_ONE_HANDED = "One-Handed Weapon",
	EQUIPMENT_TWO_HANDED = "Two-handed Weapon",
	EQUIPMENT_OUTFIT = "Outfit",
	EQUIPMENT_ACCESSORY = "Accessory",
	EQUIPMENT_SPELLBOOK = "Spellbook",
	SPELL_SCROLL = "Spell Scroll",
	RECIPE = "Recipe",
	MISC = "Misc",
}

---@enum NpcDisposition
world.NpcDisposition = {
	NEUTRAL = "Neutral",
	HOSTILE = "Hostile",
	FRIENDLY = "Friendly",
}

---@enum NpcMovementType
world.NpcMovementType = {
	SENTINEL = "Sentinel",
	WANDER = "Wander",
}

---@enum NpcBehaviorParamType
world.NpcBehaviorParamType = {
	STRING = "String",
	NUMBER = "Number",
	BOOLEAN = "Boolean",
	ITEM = "Item",
	DIRECTION = "Direction",
}

---@enum Direction
world.Direction = {
	NORTH = "north",
	EAST = "east",
	SOUTH = "south",
	WEST = "west",
}

--- Deals magic damage to a mob. Returns the number of damage dealt.
---
---@param caster_handle MobHandle
---@param target_handle MobHandle
---@param base_damage integer
---@return number
function world.deal_magic_damage(caster_handle, target_handle, base_damage) end

--- Queries the world for the requested mob data
---
--- Accepts a table of fields, where each entry is a string representing a field to get
---
--- Example: getMobData(handle, { "name" "health", "max_health"  })
--- Returns: { name: "Bufo", health" 72, max_health: 100 }
---
---@param handle MobHandle
---@param fields table
---@return table
function world.get_mob_data(handle, fields) end

--- Heals a mob with non-magic healing.
--- Returns the number of damage healed.
---
---@param target_handle MobHandle
---@param heal_amount integer
---@return number
function world.heal(target_handle, heal_amount) end

--- Logs a message to the game
---
---@param message string
function world.log(message) end

--- Heals a mob with healing that scales based on the caster and target's faith.
--- Returns the number of damage healed.
---
---@param caster_handle MobHandle
---@param target_handle MobHandle
---@param base_healing integer
---@return number
function world.magic_heal(caster_handle, target_handle, base_healing) end

--- Sends a message to the specified room
---
---@param room integer
---@param message string
function world.message_room(room, message) end

--- Returns true if the mob exists
---
---@param handle MobHandle
---@return boolean
function world.mob_exists(handle) end

--- Returns true if the mob is dead
---
---@param handle MobHandle
---@return boolean
function world.mob_is_dead(handle) end

--- Regenerates an amount of the mobs mana
--- Returns the number of mana regained.
---
---@param target_handle MobHandle
---@param regen_amount integer
---@return number
function world.regen_mana(target_handle, regen_amount) end
