---@meta
-- Code generated by go generate; DO NOT EDIT.

---@class world
world = {}

---@enum ItemKind
world.ItemKind = {
	CONSUMABLE = "Consumable",
	EQUIPMENT_ONE_HANDED = "One-Handed Weapon",
	EQUIPMENT_TWO_HANDED = "Two-handed Weapon",
	EQUIPMENT_OUTFIT = "Outfit",
	EQUIPMENT_ACCESSORY = "Accessory",
	EQUIPMENT_SPELLBOOK = "Spellbook",
	SPELL_SCROLL = "Spell Scroll",
	RECIPE = "Recipe",
	MISC = "Misc",
}

--- Logs a message to the game
---
--- Accepts an optional table of arguments. The table keys should be strings only and the
--- values can be any value. Instances of each key in the message will be replaced by the values.
---
--- Example: log("{caster} cast firebolt at {target}.", { "caster": "Bufo", "target": "Hodor" })
--- Output: "Bufo cast firebolt at Hodor."
---
---@param message string
---@param args? table
function world.log(message, args) end

--- Sends a message to the specified room
---
--- Accepts an optional table of arguments. The table keys should be strings only and the
--- values can be any value. Instances of each key in the message will be replaced by the values.
---
--- Example: messageRoom(0, "{caster} cast firebolt at {target}.", { "caster": "Bufo", "target": "Hodor" })
--- Output: "Bufo cast firebolt at Hodor."
---
---@param room integer
---@param message string
---@param args? table
function world.messageRoom(room, message, args) end
