---@meta
-- Code generated by go generate; DO NOT EDIT.

---@class world
world = {}

---An opaque reference to a mob. Compare with ==. It may refer to a mob that no longer exists; check with world.mob_exists.
---@class MobHandle

---@type number
world.SPELL_CAST_TIME_INSTANT = 0

---@type boolean
world.NPC_EVENT_PREVENT_DEFAULT = true

---@enum ItemKind
world.ItemKind = {
	CONSUMABLE = "Consumable",
	EQUIPMENT_ONE_HANDED = "One-Handed Weapon",
	EQUIPMENT_TWO_HANDED = "Two-handed Weapon",
	EQUIPMENT_OUTFIT = "Outfit",
	EQUIPMENT_ACCESSORY = "Accessory",
	EQUIPMENT_SPELLBOOK = "Spellbook",
	SPELL_SCROLL = "Spell Scroll",
	RECIPE = "Recipe",
	MISC = "Misc",
}

---@enum NpcDisposition
world.NpcDisposition = {
	NEUTRAL = "Neutral",
	HOSTILE = "Hostile",
	FRIENDLY = "Friendly",
}

---@enum NpcMode
world.NpcMode = {
	IDLE = "Idle",
	SURPRISE = "Surprise",
	AGGRO = "Aggro",
}

---@enum NpcMovementType
world.NpcMovementType = {
	SENTINEL = "Sentinel",
	WANDER = "Wander",
}

---@enum NpcBehaviorParamType
world.NpcBehaviorParamType = {
	STRING = "String",
	NUMBER = "Number",
	BOOLEAN = "Boolean",
	ITEM = "Item",
	DIRECTION = "Direction",
}

---@enum Direction
world.Direction = {
	NORTH = "north",
	EAST = "east",
	SOUTH = "south",
	WEST = "west",
}

---@enum Stat
world.Stat = {
	VIT = "VIT",
	STR = "STR",
	AGI = "AGI",
	INT = "INT",
	FTH = "FTH",
}

---@enum EquipmentSlot
world.EquipmentSlot = {
	MAIN_HAND = "Main Hand",
	OFF_HAND = "Off Hand",
	OUTFIT = "Outfit",
	ACCESSORY = "Accessory",
}

--- Deals magic damage to a mob. Returns the number of damage dealt.
---
---@param caster_handle MobHandle
---@param target_handle MobHandle
---@param base_damage integer
---@return number
function world.deal_magic_damage(caster_handle, target_handle, base_damage) end

--- Heals a mob with non-magic healing.
--- Returns the number of damage healed.
---
---@param target_handle MobHandle
---@param heal_amount integer
---@return number
function world.heal(target_handle, heal_amount) end

--- Logs a message to the game
---
---@param message string
function world.log(message) end

--- Heals a mob with healing that scales based on the caster and target's faith.
--- Returns the number of damage healed.
---
---@param caster_handle MobHandle
---@param target_handle MobHandle
---@param base_healing integer
---@return number
function world.magic_heal(caster_handle, target_handle, base_healing) end

--- Sends a message to the specified room
---
---@param room integer
---@param message string
function world.message_room(room, message) end

--- Returns true if the mob exists
---
---@param handle MobHandle
---@return boolean
function world.mob_exists(handle) end

--- Returns the name of the item the mob has equipped in a slot, or nil if the slot is empty
---
---@param handle MobHandle
---@param slot EquipmentSlot
---@return string?
function world.mob_get_equipment(handle, slot) end

--- Returns the mob's current health
---
---@param handle MobHandle
---@return integer
function world.mob_get_health(handle) end

--- Returns the mob's level
---
---@param handle MobHandle
---@return integer
function world.mob_get_level(handle) end

--- Returns the mob's current mana
---
---@param handle MobHandle
---@return integer
function world.mob_get_mana(handle) end

--- Returns the mob's max health
---
---@param handle MobHandle
---@return integer
function world.mob_get_max_health(handle) end

--- Returns the mob's max mana
---
---@param handle MobHandle
---@return integer
function world.mob_get_max_mana(handle) end

--- Returns the mob's name
---
---@param handle MobHandle
---@return string
function world.mob_get_name(handle) end

--- Returns the room the mob is in
---
---@param handle MobHandle
---@return integer
function world.mob_get_room(handle) end

--- Returns the mob's value for a stat, including equipment bonuses
---
---@param handle MobHandle
---@param stat Stat
---@return integer
function world.mob_get_stat(handle, stat) end

--- Returns true if the mob is dead
---
---@param handle MobHandle
---@return boolean
function world.mob_is_dead(handle) end

--- Returns true if the mob is an NPC
---
---@param handle MobHandle
---@return boolean
function world.mob_is_npc(handle) end

--- Returns the NPC's disposition
---
---@param handle MobHandle
---@return NpcDisposition
function world.npc_get_disposition(handle) end

--- Returns the NPC's mode
---
---@param handle MobHandle
---@return NpcMode
function world.npc_get_mode(handle) end

--- Sets the NPC's disposition
---
---@param handle MobHandle
---@param disposition NpcDisposition
function world.npc_set_disposition(handle, disposition) end

--- Sets the NPC's mode
---
---@param handle MobHandle
---@param mode NpcMode
function world.npc_set_mode(handle, mode) end

--- Regenerates an amount of the mobs mana
--- Returns the number of mana regained.
---
---@param target_handle MobHandle
---@param regen_amount integer
---@return number
function world.regen_mana(target_handle, regen_amount) end
