// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {world} from '../models';

export function ConfirmDiscardChanges():Promise<boolean>;

export function GetConstants():Promise<main.EditorConstants>;

export function GetItemData():Promise<Array<world.ItemData>>;

export function GetNpcData():Promise<Array<world.NpcData>>;

export function OpenWorld():Promise<main.EditorWorld>;

export function SaveWorld(arg1:main.EditorWorld):Promise<boolean>;

export function SaveWorldAs(arg1:main.EditorWorld):Promise<boolean>;

export function SetIsDirty(arg1:boolean):Promise<void>;
