// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {world} from '../models';

export function GetItemData():Promise<Array<world.ItemData>>;

export function GetWorld():Promise<world.World>;
