// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDiscardChanges() {
  return window['go']['main']['EditorState']['ConfirmDiscardChanges']();
}

export function GetConstants() {
  return window['go']['main']['EditorState']['GetConstants']();
}

export function GetItemData() {
  return window['go']['main']['EditorState']['GetItemData']();
}

export function GetNpcData() {
  return window['go']['main']['EditorState']['GetNpcData']();
}

export function OpenWorld() {
  return window['go']['main']['EditorState']['OpenWorld']();
}

export function SaveWorld(arg1) {
  return window['go']['main']['EditorState']['SaveWorld'](arg1);
}

export function SaveWorldAs(arg1) {
  return window['go']['main']['EditorState']['SaveWorldAs'](arg1);
}

export function SetIsDirty(arg1) {
  return window['go']['main']['EditorState']['SetIsDirty'](arg1);
}
